/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package calculadora;
/**
 *
 * @author USUARIO
 */
import javax.script.ScriptEngine;
import javax.script.ScriptEngineManager;
import javax.script.ScriptException;

public class CalculadoraApp extends javax.swing.JFrame {
    public float primerNumero;
    public float segundoNumero;
    public String operador;
    

    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(CalculadoraApp.class.getName());

    /**
     * Creates new form CalculadoraApp
     */
    public CalculadoraApp() {
        initComponents();
        this.setLocationRelativeTo(null); //Para que nuestra calculadora siempre este centrada a la hora de mostrarse
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        botonBorrar = new javax.swing.JButton();
        botonDiv = new javax.swing.JButton();
        botonMulti = new javax.swing.JButton();
        botonResta = new javax.swing.JButton();
        botonSuma = new javax.swing.JButton();
        botonNueve = new javax.swing.JButton();
        botonOcho = new javax.swing.JButton();
        botonSiete = new javax.swing.JButton();
        botonSeis = new javax.swing.JButton();
        botonCinco = new javax.swing.JButton();
        botonCuatro = new javax.swing.JButton();
        botonDos = new javax.swing.JButton();
        botonUno = new javax.swing.JButton();
        botonIgual = new javax.swing.JButton();
        botonPunto = new javax.swing.JButton();
        botonCero = new javax.swing.JButton();
        botonPotencia = new javax.swing.JButton();
        botonDiv1 = new javax.swing.JButton();
        botonTres1 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        casilla = new javax.swing.JLabel();
        casillaDos = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(462, 502));

        botonBorrar.setBackground(new java.awt.Color(55, 62, 71));
        botonBorrar.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        botonBorrar.setForeground(new java.awt.Color(55, 62, 71));
        botonBorrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/btn1.png"))); // NOI18N
        botonBorrar.setText("C");
        botonBorrar.setFocusPainted(false);
        botonBorrar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botonBorrar.setInheritsPopupMenu(true);
        botonBorrar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/btn2.png"))); // NOI18N
        botonBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonBorrarActionPerformed(evt);
            }
        });

        botonDiv.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        botonDiv.setForeground(new java.awt.Color(55, 62, 71));
        botonDiv.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/btn1.png"))); // NOI18N
        botonDiv.setText("/");
        botonDiv.setFocusPainted(false);
        botonDiv.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botonDiv.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/btn2.png"))); // NOI18N
        botonDiv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonDivActionPerformed(evt);
            }
        });

        botonMulti.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        botonMulti.setForeground(new java.awt.Color(55, 62, 71));
        botonMulti.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/btn1.png"))); // NOI18N
        botonMulti.setText("*");
        botonMulti.setFocusable(false);
        botonMulti.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botonMulti.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/btn2.png"))); // NOI18N
        botonMulti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonMultiActionPerformed(evt);
            }
        });

        botonResta.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        botonResta.setForeground(new java.awt.Color(55, 62, 71));
        botonResta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/btn1.png"))); // NOI18N
        botonResta.setText("-");
        botonResta.setFocusable(false);
        botonResta.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botonResta.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/btn2.png"))); // NOI18N
        botonResta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRestaActionPerformed(evt);
            }
        });

        botonSuma.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        botonSuma.setForeground(new java.awt.Color(55, 62, 71));
        botonSuma.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/btn1.png"))); // NOI18N
        botonSuma.setText("+");
        botonSuma.setFocusable(false);
        botonSuma.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botonSuma.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/btn2.png"))); // NOI18N
        botonSuma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSumaActionPerformed(evt);
            }
        });

        botonNueve.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        botonNueve.setForeground(new java.awt.Color(55, 62, 71));
        botonNueve.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/btn3.png"))); // NOI18N
        botonNueve.setText("9");
        botonNueve.setFocusPainted(false);
        botonNueve.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botonNueve.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/btn2.png"))); // NOI18N
        botonNueve.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonNueveActionPerformed(evt);
            }
        });

        botonOcho.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        botonOcho.setForeground(new java.awt.Color(55, 62, 71));
        botonOcho.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/btn3.png"))); // NOI18N
        botonOcho.setText("8");
        botonOcho.setFocusPainted(false);
        botonOcho.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botonOcho.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/btn2.png"))); // NOI18N
        botonOcho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonOchoActionPerformed(evt);
            }
        });

        botonSiete.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        botonSiete.setForeground(new java.awt.Color(55, 62, 71));
        botonSiete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/btn3.png"))); // NOI18N
        botonSiete.setText("7");
        botonSiete.setFocusable(false);
        botonSiete.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botonSiete.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/btn2.png"))); // NOI18N
        botonSiete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSieteActionPerformed(evt);
            }
        });

        botonSeis.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        botonSeis.setForeground(new java.awt.Color(55, 62, 71));
        botonSeis.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/btn3.png"))); // NOI18N
        botonSeis.setText("6");
        botonSeis.setFocusable(false);
        botonSeis.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botonSeis.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/btn2.png"))); // NOI18N
        botonSeis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSeisActionPerformed(evt);
            }
        });

        botonCinco.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        botonCinco.setForeground(new java.awt.Color(55, 62, 71));
        botonCinco.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/btn3.png"))); // NOI18N
        botonCinco.setText("5");
        botonCinco.setFocusPainted(false);
        botonCinco.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botonCinco.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/btn2.png"))); // NOI18N
        botonCinco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCincoActionPerformed(evt);
            }
        });

        botonCuatro.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        botonCuatro.setForeground(new java.awt.Color(55, 62, 71));
        botonCuatro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/btn3.png"))); // NOI18N
        botonCuatro.setText("4");
        botonCuatro.setFocusPainted(false);
        botonCuatro.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botonCuatro.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/btn2.png"))); // NOI18N
        botonCuatro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCuatroActionPerformed(evt);
            }
        });

        botonDos.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        botonDos.setForeground(new java.awt.Color(55, 62, 71));
        botonDos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/btn3.png"))); // NOI18N
        botonDos.setText("2");
        botonDos.setFocusable(false);
        botonDos.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botonDos.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/btn2.png"))); // NOI18N
        botonDos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonDosActionPerformed(evt);
            }
        });

        botonUno.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        botonUno.setForeground(new java.awt.Color(55, 62, 71));
        botonUno.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/btn3.png"))); // NOI18N
        botonUno.setText("1");
        botonUno.setFocusable(false);
        botonUno.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botonUno.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/btn2.png"))); // NOI18N
        botonUno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonUnoActionPerformed(evt);
            }
        });

        botonIgual.setBackground(new java.awt.Color(255, 153, 51));
        botonIgual.setFont(new java.awt.Font("Segoe UI Black", 0, 36)); // NOI18N
        botonIgual.setForeground(new java.awt.Color(255, 255, 255));
        botonIgual.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/btn4.png"))); // NOI18N
        botonIgual.setText("=");
        botonIgual.setFocusable(false);
        botonIgual.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botonIgual.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/btn5.png"))); // NOI18N
        botonIgual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonIgualActionPerformed(evt);
            }
        });

        botonPunto.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        botonPunto.setForeground(new java.awt.Color(55, 62, 71));
        botonPunto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/btn3.png"))); // NOI18N
        botonPunto.setText(".");
        botonPunto.setFocusable(false);
        botonPunto.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botonPunto.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/btn2.png"))); // NOI18N
        botonPunto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonPuntoActionPerformed(evt);
            }
        });

        botonCero.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        botonCero.setForeground(new java.awt.Color(55, 62, 71));
        botonCero.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/btn3.png"))); // NOI18N
        botonCero.setText("0");
        botonCero.setFocusable(false);
        botonCero.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botonCero.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/btn2.png"))); // NOI18N
        botonCero.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/btn2.png"))); // NOI18N
        botonCero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCeroActionPerformed(evt);
            }
        });

        botonPotencia.setBackground(new java.awt.Color(55, 62, 71));
        botonPotencia.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        botonPotencia.setForeground(new java.awt.Color(55, 62, 71));
        botonPotencia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/btn1.png"))); // NOI18N
        botonPotencia.setText("^");
        botonPotencia.setFocusPainted(false);
        botonPotencia.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botonPotencia.setInheritsPopupMenu(true);
        botonPotencia.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/btn2.png"))); // NOI18N
        botonPotencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonPotenciaActionPerformed(evt);
            }
        });

        botonDiv1.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        botonDiv1.setForeground(new java.awt.Color(55, 62, 71));
        botonDiv1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/btn1.png"))); // NOI18N
        botonDiv1.setText("%");
        botonDiv1.setFocusPainted(false);
        botonDiv1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botonDiv1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/btn2.png"))); // NOI18N
        botonDiv1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonDiv1ActionPerformed(evt);
            }
        });

        botonTres1.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        botonTres1.setForeground(new java.awt.Color(55, 62, 71));
        botonTres1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/btn3.png"))); // NOI18N
        botonTres1.setText("3");
        botonTres1.setFocusable(false);
        botonTres1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botonTres1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/btn2.png"))); // NOI18N
        botonTres1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonTres1ActionPerformed(evt);
            }
        });

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/btn6.png"))); // NOI18N
        jButton1.setFocusPainted(false);
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/btn7.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(botonBorrar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(botonPotencia, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(botonDiv1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(botonSiete, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(botonOcho, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(botonNueve, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(botonMulti, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(botonDiv, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(botonUno, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(botonCero, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(botonPunto, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(botonDos, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(botonTres1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(botonIgual, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(botonSuma, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(botonCuatro, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(botonCinco, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(botonSeis, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(botonResta, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(10, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(botonBorrar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(botonPotencia, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(botonDiv, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addComponent(botonDiv1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonMulti, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonNueve, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonOcho, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonSiete, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botonSeis, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(botonCinco, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(botonCuatro, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(botonResta, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(botonUno, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(botonDos, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addComponent(botonTres1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(botonSuma, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(botonCero, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(botonPunto, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(botonIgual, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 430, 500));

        jPanel2.setBackground(new java.awt.Color(204, 255, 255));

        casilla.setBackground(new java.awt.Color(14, 13, 13));
        casilla.setFont(new java.awt.Font("Segoe UI Black", 0, 48)); // NOI18N
        casilla.setForeground(new java.awt.Color(55, 62, 71));
        casilla.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        casillaDos.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        casillaDos.setForeground(new java.awt.Color(55, 62, 71));
        casillaDos.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        casillaDos.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(casilla, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(casillaDos, javax.swing.GroupLayout.DEFAULT_SIZE, 430, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(casillaDos, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(casilla, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(9, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 430, 160));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void botonBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonBorrarActionPerformed
        // TODO add your handling code here:
        this.casilla.setText("");
        this.casillaDos.setText("");
    }//GEN-LAST:event_botonBorrarActionPerformed

    private void botonDivActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonDivActionPerformed
        // TODO add your handling code here:
        addNumber("/");
        this.primerNumero = Float.parseFloat(this.casilla.getText());
        this.operador = "/";
        this.casilla.setText("");
    }//GEN-LAST:event_botonDivActionPerformed

    private void botonCeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCeroActionPerformed
        // TODO add your handling code here:
        addNumber("0");
         this.casilla.setText(casilla.getText() + "0");
    }//GEN-LAST:event_botonCeroActionPerformed

    private void botonUnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonUnoActionPerformed
        // TODO add your handling code here:
        addNumber("1");
         this.casilla.setText(casilla.getText() + "1");
    }//GEN-LAST:event_botonUnoActionPerformed

    private void botonCuatroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCuatroActionPerformed
        // TODO add your handling code here:
        addNumber("4");
         this.casilla.setText(casilla.getText() + "4");
    }//GEN-LAST:event_botonCuatroActionPerformed

    private void botonCincoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCincoActionPerformed
        // TODO add your handling code here:
        addNumber("5");
         this.casilla.setText(casilla.getText() + "5");
    }//GEN-LAST:event_botonCincoActionPerformed

    private void botonSeisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSeisActionPerformed
        // TODO add your handling code here:
        addNumber("6");
         this.casilla.setText(casilla.getText() + "6");
    }//GEN-LAST:event_botonSeisActionPerformed

    private void botonSieteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSieteActionPerformed
        // TODO add your handling code here:
        addNumber("7");
         this.casilla.setText(casilla.getText() + "7");
       
    }//GEN-LAST:event_botonSieteActionPerformed

    private void botonOchoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonOchoActionPerformed
        // TODO add your handling code here:
       addNumber("8");
        this.casilla.setText(casilla.getText() + "8");
    }//GEN-LAST:event_botonOchoActionPerformed

    private void botonNueveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonNueveActionPerformed
        // TODO add your handling code here:
        addNumber("9");
        this.casilla.setText(casilla.getText() + "9");
    }//GEN-LAST:event_botonNueveActionPerformed

    private void botonSumaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSumaActionPerformed
        // TODO add your handling code here:
        addNumber("+");
        this.primerNumero = Float.parseFloat(this.casilla.getText());
        this.operador = "+";
        this.casilla.setText("");
        
    }//GEN-LAST:event_botonSumaActionPerformed

    private void botonIgualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonIgualActionPerformed
        // TODO add your handling code here:
        this.segundoNumero = Float.parseFloat(this.casilla.getText());
        
        switch (this.operador) {
            case "+" -> this.casilla.setText(recorte(this.segundoNumero + this.primerNumero));
            case "-" -> this.casilla.setText(recorte(this.primerNumero - this.segundoNumero));
            case "*" -> this.casilla.setText(recorte( this.primerNumero * this.segundoNumero));
            case "/" -> {
                                        if(this.segundoNumero == 0){
                                                this.casilla.setText("NoSeDivideEntreCero");
                                        }else{
                                                this.casilla.setText(recorte(this.primerNumero / this.segundoNumero));
                                        }
            
                            }
            case "%" ->this.casilla.setText(recorte(this.primerNumero % this.segundoNumero));
            case "^" -> {
                            double resultadoE = Math.pow(this.primerNumero, this.segundoNumero);
                            this.casilla.setText(recorte((float) resultadoE));
                            
                    }
          } 
    }//GEN-LAST:event_botonIgualActionPerformed

    private void botonRestaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRestaActionPerformed
        // TODO add your handling code here:
        addNumber("-");
        this.primerNumero = Float.parseFloat(this.casilla.getText());
        this.operador = "-";
        this.casilla.setText("");
    }//GEN-LAST:event_botonRestaActionPerformed

    private void botonMultiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonMultiActionPerformed
        // TODO add your handling code here:
        addNumber("*");
        this.primerNumero = Float.parseFloat(this.casilla.getText());
        this.operador = "*";
        this.casilla.setText("");
    }//GEN-LAST:event_botonMultiActionPerformed

    private void botonPuntoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonPuntoActionPerformed
        // TODO add your handling code here:
        if(!(this.casilla.getText().contains("."))){
                this.casilla.setText(this.casilla.getText() + " . ");
        }
    }//GEN-LAST:event_botonPuntoActionPerformed

    private void botonPotenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonPotenciaActionPerformed
        // TODO add your handling code here:
        addNumber("^");
        this.primerNumero = Float.parseFloat(this.casilla.getText());
        operador = "^";
        this.casilla.setText("");
    }//GEN-LAST:event_botonPotenciaActionPerformed

    private void botonDiv1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonDiv1ActionPerformed
        // TODO add your handling code here:
        addNumber("%");
        this.primerNumero =Float.parseFloat(this.casilla.getText());
        this.operador = "%";
        this.casilla.setText("");
    }//GEN-LAST:event_botonDiv1ActionPerformed

    private void botonTres1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonTres1ActionPerformed
        // TODO add your handling code here:
        addNumber("3");
         this.casilla.setText(casilla.getText() + "3");
    }//GEN-LAST:event_botonTres1ActionPerformed

    private void botonDosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonDosActionPerformed
        // TODO add your handling code here:
        addNumber("2");
        this.casilla.setText(casilla.getText() + "2");
    }//GEN-LAST:event_botonDosActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
       String operacion = casillaDos.getText();

    if (!operacion.isEmpty()) {
        // Borra el último carácter
        operacion = operacion.substring(0, operacion.length() - 1);
        casillaDos.setText(operacion);

        // Intenta calcular el nuevo resultado si queda algo válido
        try {
            if (!operacion.isEmpty() && !terminaEnOperador(operacion)) {
                // Evaluar operación con ScriptEngine
                ScriptEngine engine = new ScriptEngineManager().getEngineByName("JavaScript");
                Object resultado = engine.eval(operacion);
                casilla.setText(resultado.toString());
            } else {
                casilla.setText(""); // Si termina en operador, vacía el resultado
            }
        } catch (ScriptException e) {
            casilla.setText(""); // En caso de error (por ejemplo, expresión inválida)
        }
    }
            
        
    }//GEN-LAST:event_jButton1ActionPerformed
 
    // Verifica si el string termina en un operador matemático
private boolean terminaEnOperador(String texto) {
    return texto.endsWith("+") || texto.endsWith("-") || texto.endsWith("*") || texto.endsWith("/");
}

    public String recorte(float resultado){
        String retorno;
        
        retorno = Float.toString(resultado);
        
        if(resultado % 1 == 0){
            retorno = retorno.substring(0, retorno.length() - 2); //le quitamos los 2 ultimos caracteres que terminan en .0 ,recorta con subtring
        }
        
        return retorno;
        
    }
    
    public void addNumber(String digito){
        this.casillaDos.setText(casillaDos.getText() + digito);
        this.casilla.setText(casilla.getText()  );
 
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new CalculadoraApp().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonBorrar;
    private javax.swing.JButton botonCero;
    private javax.swing.JButton botonCinco;
    private javax.swing.JButton botonCuatro;
    private javax.swing.JButton botonDiv;
    private javax.swing.JButton botonDiv1;
    private javax.swing.JButton botonDos;
    private javax.swing.JButton botonIgual;
    private javax.swing.JButton botonMulti;
    private javax.swing.JButton botonNueve;
    private javax.swing.JButton botonOcho;
    private javax.swing.JButton botonPotencia;
    private javax.swing.JButton botonPunto;
    private javax.swing.JButton botonResta;
    private javax.swing.JButton botonSeis;
    private javax.swing.JButton botonSiete;
    private javax.swing.JButton botonSuma;
    private javax.swing.JButton botonTres1;
    private javax.swing.JButton botonUno;
    private javax.swing.JLabel casilla;
    private javax.swing.JLabel casillaDos;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
